import = ["~/dotfiles/theme/palette.toml"]

[bell]
duration = 10

[font]
size = 19.0

[font.normal]
family = "NotoMono Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
decorations = "full"
option_as_alt = "Both"
startup_mode = "Maximized"

[[keyboard.bindings]]
key = "Enter"
mods = "Shift"
chars = "\u001b\r"
