[colors.primary]
background = "#292522"
foreground = "#ECE1D7"
bright_foreground = "#ECE1D7"
dim_foreground = "#403A36"

[colors.cursor]
text = "#292522"
cursor = "#ECE1D7"

[colors.vi_mode_cursor]
text = "#292522"
cursor = "#ECE1D7"

[colors.selection]
text = "CellForeground"
background = "#A3A9CE"

[colors.normal]
black = "#34302C"
blue = "#7F91B2"
cyan = "#7B9695"
green = "#78997A"
magenta = "#B380B0"
red = "#BD8183"
white = "#C1A78E"
yellow = "#E49B5D"

[colors.bright]
black = "#867462"
blue = "#A3A9CE"
cyan = "#89B3B6"
green = "#85B695"
magenta = "#CF9BC2"
red = "#D47766"
white = "#ECE1D7"
yellow = "#EBC06D"

[colors.dim]
black = "#292522"
blue = "#273142"
cyan = "#253333"
green = "#233524"
magenta = "#422741"
red = "#7D2A2F"
white = "#403A36"
yellow = "#8B7449"
