[".zsh/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"

[".zsh/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"

[".zsh/plugins/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    refreshPeriod = "168h"
