#!/bin/bash

#nvm se#tup
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
nvm install 0.12
nvm install node
nvm alias default node

#global installs
PACKAGES=(ember-cli bower express-generator http-server knex nodemon mocha phantomjs)

npm install -g $(echo ${PACKAGES[*]})
