#!/bin/bash

#General
sudo apt-get update
sudo apt-get -y upgrade
PACKAGES=(curl wget git xclip tmux vim ranger nmap tree fonts-powerline zsh silversearcher-ag)
sudo apt-get install -y $(echo ${PACKAGES[*]})

#Heroku
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
