#!/bin/bash

# Link the docker compose file and put in the PATH
ln -sf ~/dotfiles/docker-compose.yml ~/docker-compose.yml
sudo ln -sf ~/dotfiles/dev /usr/local/bin/dev

# Install oh-my-zsh and link the theme
OHMYZSH_DIR='/home/kylecoberly/.oh-my-zsh'
if [ ! -d "${OHMYZSH_DIR}" ]
then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
ln -sf ~/dotfiles/dotfiles/coberly-agnoster.zsh-theme ~/.oh-my-zsh/themes

#Remove old dotfiles and replace them for the host machine
DOTFILES=(.gitconfig .bashrc .zshrc .aliases .vimrc .rvmrc .tmux .tmux.conf) 
for dotfile in $(echo ${DOTFILES[*]});
do
    sudo rm -rf ~/$(echo $dotfile)
    ln -sf ~/dotfiles/dotfiles/$(echo $dotfile) ~/$(echo $dotfile)
done
