#!/bin/bash

DOTFILES=(.gitconfig .tmux .tmux.conf .bashrc .zshrc .aliases .vimrc) 

#Remove old dotfiles and replace them
for dotfile in $(echo ${DOTFILES[*]});
do
    sudo rm -rf ~/$(echo $dotfile)
    ln -sf ~/dotfiles/$(echo $dotfile) ~/$(echo $dotfile)
done

# Set oh-my-zsh theme
ln -sf ~/dotfiles/coberly-agnoster.zsh-theme ~/.oh-my-zsh/themes/coberly-agnoster.zsh-theme
