#!/bin/bash

SCRIPTS=(serena paul)

#Remove old dotfiles and replace them
for script in $(echo ${SCRIPTS[*]});
do
    sudo rm -rf /usr/bin/$(echo $script)
    sudo ln -s ~/dotfiles/$(echo $script) /usr/bin/$(echo $script)
done
