return {
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   {
  --     opts = function(_, opts)
  --       if type(opts.ensure_installed) == "table" then
  --         vim.list_extend(opts.ensure_installed, { "typescript", "tsx", "json", "json5", "jsonc" })
  --       end
  --     end,
  --   },
  -- },
  -- -- add any tools you want to have installed below
  -- {
  --   "williamboman/mason.nvim",
  --   opts = {
  --     ensure_installed = {
  --       "stylua",
  --       "shellcheck",
  --       "shfmt",
  --       "flake8",
  --     },
  --   },
  -- },
}
